# Configuration File -- it's TOML

[logs]
logfile = "log.txt"

[rekognition]
image_types = [ ".png", ".jpg", ".jpeg" ]
check_types = [ "detect_labels", "detect_moderation_labels" ]
file_types = [ ".mp4", ".mp3", ".torrent", ".bad", ".sad" ]

[discord]
auth_token = ""

[piracy]


#[language]
#tone
#explicit
#topics